services:
  app:
    image: optikt-app
    ports:
      - '3000:3000'
    environment:
      ORIGIN: http://localhost:3000
      DATABASE_URL: postgres://optikt:Optikt_123@host.docker.internal:5432/optikt_db
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped