<script lang="ts">
	import { toast } from 'svelte-sonner';
	import { goto } from '$app/navigation';
	import { untrack } from 'svelte';
	import {
		createLensCatalogItemForm,
		updateLensCatalogItemForm,
		listTechnologiesBySupplier
	} from '$lib/remote/lenses.remote';
	import { type SelectOption, type PendingEntity } from '$lib/components/ui';
	import { getErrorMessage, logger } from '$lib/utils';
	import FormActions from '$lib/components/ui/FormActions.svelte';
	import LensFormIdentitySection from './form/LensFormIdentitySection.svelte';
	import LensFormCostSection from './form/LensFormCostSection.svelte';
	import LensFormManagementSection from './form/LensFormManagementSection.svelte';
	import LensFormRangesSection from './form/LensFormRangesSection.svelte';
	import {
		getPendingName as getPendingNameHelper,
		handleCreatePending
	} from './form/lensFormPending';
	import { buildAutoGeneratedName } from './form/lensFormDisplay';
	import {
		addRange as addRangeHelper,
		buildServerRangeValidations,
		getRootRangeIssues,
		removeRange as removeRangeHelper,
		toastUnboundNonRangeIssues,
		toggleSphereMode as toggleSphereModeHelper
	} from './form/lensFormRanges';
	import {
		collapseOpticalRangesForForm,
		createEmptyOpticalRangeEntry,
		expandOpticalRanges,
		hasOpticalRangeValidationErrors,
		validateOpticalRangeEntry,
		type OpticalRangeFormEntry
	} from '$lib/utils/opticalRangeForm';
	import {
		LensType,
		LensCatalogSource,
		LensPriceType,
		LensInventoryMode
	} from '$lib/shared/enums';
	import { scrollToFirstError, getFormErrorMessage } from '$lib/utils';
	import { generateUUID } from '$lib/utils/generateUUID';
	import type { LensCatalogItem, LensOpticalRange } from '$lib/server/db/schema';
	import { resolve } from '$app/paths';

	type Props = {
		item?: LensCatalogItem | null;
		existingRanges?: LensOpticalRange[];
		materials: { id: string; name: string }[];
		suppliers: { id: string; name: string }[];
		differentiators?: string[];
		supplierTechnologies?: { id: string; name: string }[];
		technologyIsGlobal?: boolean;
		cancelHref?: string;
		formId?: string;
		showActions?: boolean;
		isSubmitting?: boolean;
	};

	let {
		item = null,
		existingRanges = [],
		materials = [],
		suppliers = [],
		differentiators = [],
		supplierTechnologies: initialSupplierTechnologies = [],
		technologyIsGlobal: initialTechnologyIsGlobal = false,
		cancelHref = '/lenses',
		formId = 'lens-catalog-form',
		showActions = true,
		isSubmitting = $bindable(false)
	}: Props = $props();

	// Capture initial values (item comes from PageServerLoad, doesn't change)
	const initialItem = untrack(() => item);
	const initialRanges = untrack(() => existingRanges);

	const isEdit = $derived(!!item);

	// Form instance
	let formInstanceId = $state(generateUUID());

	const currentCreateForm = $derived(createLensCatalogItemForm.for(formInstanceId));
	const currentUpdateForm = $derived(
		updateLensCatalogItemForm.for(`${item?.id}-${formInstanceId}`)
	);
	const activeForm = $derived(isEdit ? currentUpdateForm : currentCreateForm);

	// Pending entities
	let pendingSuppliers = $state<PendingEntity[]>([]);
	let pendingMaterials = $state<PendingEntity[]>([]);
	let pendingTechnologies = $state<PendingEntity[]>([]);

	// Form data - numeric fields are strings because they bind to <Input type="number">
	let formData = $state({
		source: (initialItem?.source as LensCatalogSource) ?? LensCatalogSource.LAB,
		supplierId: initialItem?.supplierId ?? '',
		name: initialItem?.name ?? '',
		type: (initialItem?.type as LensType) ?? LensType.MONOFOCAL,
		technologyId: initialItem?.technologyId ?? '',
		differentiators: (initialItem?.differentiators as string[]) ?? [],
		arColors: (initialItem?.arColors as string[]) ?? [],
		photochromicColors: (initialItem?.photochromicColors as string[]) ?? [],
		materialId: initialItem?.materialId ?? '',
		// Inherent traits
		hasAr: initialItem?.hasAr ?? false,
		hasBluecut: initialItem?.hasBluecut ?? false,
		isPhotochromic: initialItem?.isPhotochromic ?? false,
		// Pricing
		priceType: (initialItem?.priceType as LensPriceType) ?? LensPriceType.UNIT,
		basePrice: initialItem?.basePrice?.toString() ?? '0',
		salePrice: initialItem?.salePrice?.toString() ?? '0',
		mountingPrice: initialItem?.mountingPrice?.toString() ?? '0',
		shippingPrice: initialItem?.shippingPrice?.toString() ?? '0',
		// Tax
		isTaxable: initialItem?.isTaxable ?? false,
		// Inventory
		inventoryMode: (initialItem?.inventoryMode as LensInventoryMode) ?? LensInventoryMode.ON_DEMAND,
		stock: initialItem?.stock != null ? initialItem.stock.toString() : '0',
		notes: initialItem?.notes ?? ''
	});

	// Comma-separated text states for arrays
	let differentiatorsText = $state(
		initialItem?.differentiators ? (initialItem.differentiators as string[]).join(', ') : ''
	);
	let arColorsText = $state(
		initialItem?.arColors ? (initialItem.arColors as string[]).join(', ') : ''
	);
	let photochromicColorsText = $state(
		initialItem?.photochromicColors ? (initialItem.photochromicColors as string[]).join(', ') : ''
	);

	// Reactively update array fields from comma-separated inputs
	$effect(() => {
		formData.differentiators = differentiatorsText
			.split(',')
			.map((s) => s.trim())
			.filter(Boolean);
	});
	$effect(() => {
		formData.arColors = arColorsText
			.split(',')
			.map((s) => s.trim())
			.filter(Boolean);
	});
	$effect(() => {
		formData.photochromicColors = photochromicColorsText
			.split(',')
			.map((s) => s.trim())
			.filter(Boolean);
	});

	// Dynamic supplier technologies list
	let supplierTechnologies = $state<Array<{ id: string; name: string }>>(
		untrack(() => initialSupplierTechnologies)
	);
	let isGlobalTechnology = $state(untrack(() => initialTechnologyIsGlobal));

	function handleSupplierChange(selected: { id: string; name: string } | null) {
		const supplierId = selected?.id ?? '';
		formData.supplierId = supplierId;
		formData.technologyId = '';
		listTechnologiesBySupplier({
			supplierId: supplierId && !supplierId.startsWith('pending_') ? supplierId : undefined
		})
			.then((res) => {
				supplierTechnologies = res;
			})
			.catch((err) => {
				logger.error('Error cargando tecnologías del proveedor', err);
				supplierTechnologies = [];
			});
	}

	// Pricing display moved to LensFormCostSection (computes internally via calculateLensPricing)

	// Dynamic optical ranges
	let ranges = $state<OpticalRangeFormEntry[]>(
		initialRanges.length > 0 ? collapseOpticalRangesForForm(initialRanges) : []
	);

	// Start with one empty range for FINISHED lenses (new items only)
	$effect(() => {
		if (ranges.length === 0 && !item) {
			untrack(() => {
				if (formData.source === LensCatalogSource.FINISHED) {
					ranges = [createEmptyOpticalRangeEntry()];
				}
			});
		}
	});

	// Force ON_DEMAND when source is LAB
	$effect(() => {
		if (formData.source === LensCatalogSource.LAB) {
			untrack(() => {
				formData.inventoryMode = LensInventoryMode.ON_DEMAND;
			});
		}
	});

	const showAddition = $derived(
		formData.type === LensType.PROGRESSIVE ||
			formData.type === LensType.BIFOCAL ||
			formData.type === LensType.OCCUPATIONAL
	);

	// Material/supplier options for CreatableSelect
	const materialOptions = $derived<SelectOption[]>(
		materials.map((m) => ({
			id: m.id,
			name: m.name
		}))
	);

	const supplierOptions = $derived<SelectOption[]>(
		suppliers.map((s) => ({ id: s.id, name: s.name }))
	);

	const supplierHelperText = $derived.by(() => {
		if (!formData.supplierId) return 'Selecciona o crea el proveedor responsable de este lente.';
		if (formData.supplierId.startsWith('pending_')) {
			return 'Este proveedor no existe. Se creara un nuevo registro al guardar.';
		}
		return 'Este proveedor ya esta registrado en el sistema.';
	});

	const materialHelperText = $derived.by(() => {
		if (!formData.materialId) return 'Selecciona o crea el material base del cristal.';
		if (formData.materialId.startsWith('pending_')) {
			return 'Este material no existe. Se creara un nuevo registro al guardar.';
		}
		return 'Este material ya esta registrado y listo para reutilizar.';
	});

	const technologyHelperText =
		'Selecciona la tecnología de fabricación digital para este lente de laboratorio.';

	const differentiatorHelperText = $derived.by(() =>
		differentiators.length > 0
			? `Opcional: etiquetas descriptivas separadas por comas (sugeridas: ${differentiators.slice(0, 3).join(', ')}).`
			: 'Opcional: etiquetas descriptivas separadas por comas (ej. Cilindro Alto 2, UV400).'
	);

	// Auto-name generation
	let autoNameEnabled = $state(true);

	const autoGeneratedName = $derived.by(() => {
		if (!autoNameEnabled) return '';
		return buildAutoGeneratedName(
			formData,
			{ suppliers, materials, supplierTechnologies },
			{ pendingSuppliers, pendingMaterials, pendingTechnologies }
		);
	});

	// Apply auto-name when deps change
	$effect(() => {
		const name = autoGeneratedName;
		if (autoNameEnabled && name) {
			untrack(() => {
				formData.name = name;
			});
		}
	});

	// Range helpers — logic moved to ./form/lensFormRanges.ts, wrappers keep $state reactivity
	function addRange() {
		ranges = addRangeHelper(ranges);
	}

	function removeRange(index: number) {
		ranges = removeRangeHelper(ranges, index);
	}

	function toggleSphereMode(range: OpticalRangeFormEntry) {
		toggleSphereModeHelper(range);
	}

	const serializedRanges = $derived(JSON.stringify(expandOpticalRanges(ranges)));

	// Range validation helpers moved to ./form/lensFormRanges.ts — imported above

	const clientRangeValidations = $derived.by(() =>
		ranges.map((r) =>
			validateOpticalRangeEntry(r, {
				requireAddition: showAddition,
				skipAddition: !showAddition
			})
		)
	);
	const hasClientRangeErrors = $derived.by(() =>
		clientRangeValidations.some(hasOpticalRangeValidationErrors)
	);
	const rangeServerIssues = $derived.by(() => activeForm.fields.allIssues?.() ?? []);
	const serverRangeValidations = $derived.by(() => buildServerRangeValidations(rangeServerIssues));
	const rootRangeIssues = $derived.by(() => getRootRangeIssues(rangeServerIssues));

	async function runValidatedSubmit(
		submit: () => Promise<unknown>,
		onSuccess: () => void,
		fallbackMessage: string
	) {
		isSubmitting = true;

		try {
			if (hasClientRangeErrors) {
				toast.error('Corrige los errores marcados en los rangos ópticos');
				scrollToFirstError();
				return;
			}

			await submit();
			onSuccess();
		} catch (e) {
			toast.error(getErrorMessage(e, fallbackMessage));
		} finally {
			isSubmitting = false;
		}
	}

	function handleCreatePendingSupplier(name: string): SelectOption {
		const result = handleCreatePending(pendingSuppliers, name, 'pending_supplier');
		pendingSuppliers = result.updatedList;
		return result.option;
	}

	function handleCreatePendingMaterial(name: string): SelectOption {
		const result = handleCreatePending(pendingMaterials, name, 'pending_material');
		pendingMaterials = result.updatedList;
		return result.option;
	}

	function handleCreatePendingTechnology(name: string): SelectOption {
		const result = handleCreatePending(pendingTechnologies, name, 'pending_technology');
		pendingTechnologies = result.updatedList;
		return result.option;
	}

	function getPendingName(pendingId: string): string | null {
		return getPendingNameHelper(pendingId, pendingSuppliers, pendingMaterials, pendingTechnologies);
	}

	function handleCreateResult() {
		const allIssues = currentCreateForm.fields.allIssues?.() ?? [];
		if (allIssues.length > 0) {
			toast.error('Por favor corrige los errores del formulario');
			scrollToFirstError();
			toastUnboundNonRangeIssues(allIssues);
			return;
		}
		const result = currentCreateForm.result;
		const createdId =
			typeof result === 'object' &&
			result !== null &&
			'id' in result &&
			typeof result.id === 'string'
				? result.id
				: null;
		toast.success('Lente agregado al catálogo');
		goto(resolve(createdId ? `/lenses/${createdId}` : '/lenses'));
	}

	function handleUpdateResult() {
		const allIssues = currentUpdateForm.fields.allIssues?.() ?? [];
		if (allIssues.length > 0) {
			toast.error('Por favor corrige los errores del formulario');
			scrollToFirstError();
			toastUnboundNonRangeIssues(allIssues);
			return;
		}
		toast.success('Lente actualizado');
		goto(resolve(`/lenses/${item!.id}`));
	}
</script>

<div class="w-full">
	{#if isEdit && item}
		<form
			id={formId}
			{...currentUpdateForm.enhance(async ({ submit }) => {
				await runValidatedSubmit(submit, handleUpdateResult, 'Error actualizando lente');
			})}
			class="space-y-6"
		>
			<input type="hidden" name="id" value={item.id} />
			{@render pendingHiddenInputs()}
			{@render formFields()}
			{#if showActions}
				{@render formActions()}
			{/if}
		</form>
	{:else}
		<form
			id={formId}
			{...currentCreateForm.enhance(async ({ submit }) => {
				await runValidatedSubmit(submit, handleCreateResult, 'Error creando lente');
			})}
			class="space-y-6"
		>
			{@render pendingHiddenInputs()}
			{@render formFields()}
			{#if showActions}
				{@render formActions()}
			{/if}
		</form>
	{/if}
</div>

{#snippet pendingHiddenInputs()}
	{#if formData.supplierId?.startsWith('pending_')}
		<input
			type="hidden"
			name="pendingSupplierName"
			value={getPendingName(formData.supplierId) ?? ''}
		/>
	{/if}
	{#if formData.materialId?.startsWith('pending_material_')}
		<input
			type="hidden"
			name="pendingMaterialName"
			value={getPendingName(formData.materialId) ?? ''}
		/>
	{/if}
	{#if formData.technologyId?.startsWith('pending_technology_')}
		<input
			type="hidden"
			name="pendingTechnologyName"
			value={getPendingName(formData.technologyId) ?? ''}
		/>
	{/if}
{/snippet}

{#snippet formFields()}
	<input type="hidden" name="source" value={formData.source} />
	<input type="hidden" name="hasAr" value={String(formData.hasAr)} />
	<input type="hidden" name="hasBluecut" value={String(formData.hasBluecut)} />
	<input type="hidden" name="isPhotochromic" value={String(formData.isPhotochromic)} />
	<input type="hidden" name="isGlobalTechnology" value={String(isGlobalTechnology)} />
	<input type="hidden" name="priceType" value={formData.priceType} />
	<input type="hidden" name="ranges" value={serializedRanges} />
	<input type="hidden" name="differentiators" value={JSON.stringify(formData.differentiators)} />
	<input type="hidden" name="arColors" value={JSON.stringify(formData.arColors)} />
	<input
		type="hidden"
		name="photochromicColors"
		value={JSON.stringify(formData.photochromicColors)}
	/>

	<div class="grid grid-cols-1 gap-6 lg:grid-cols-12">
		<div class="space-y-6 lg:col-span-7">
			<LensFormIdentitySection
				bind:formData
				supplierOptions={supplierOptions}
				materialOptions={materialOptions}
				supplierTechnologies={supplierTechnologies}
				bind:isGlobalTechnology
				supplierHelperText={supplierHelperText}
				materialHelperText={materialHelperText}
				technologyHelperText={technologyHelperText}
				differentiatorHelperText={differentiatorHelperText}
				supplierError={activeForm.fields.supplierId?.issues()
					? getFormErrorMessage(activeForm.fields.supplierId.issues())
					: null}
				materialError={activeForm.fields.materialId?.issues()
					? getFormErrorMessage(activeForm.fields.materialId.issues())
					: null}
				nameError={activeForm.fields.name?.issues()
					? getFormErrorMessage(activeForm.fields.name.issues())
					: null}
				bind:autoNameEnabled
				bind:differentiatorsText
				bind:arColorsText
				bind:photochromicColorsText
				onSupplierChange={handleSupplierChange}
				onCreatePendingSupplier={handleCreatePendingSupplier}
				onCreatePendingMaterial={handleCreatePendingMaterial}
				onCreatePendingTechnology={handleCreatePendingTechnology}
			/>
			<LensFormRangesSection
				ranges={ranges}
				clientValidations={clientRangeValidations}
				serverValidations={serverRangeValidations}
				rootRangeIssues={rootRangeIssues}
				showAddition={showAddition}
				source={formData.source}
				onAddRange={addRange}
				onRemoveRange={removeRange}
				onToggleSphereMode={toggleSphereMode}
			/>
		</div>

		<div class="space-y-6 lg:col-span-5">
			<LensFormCostSection bind:formData />

			<LensFormManagementSection bind:formData />
		</div>
	</div>
{/snippet}

{#snippet formActions()}
	<FormActions
		primaryLabel={isEdit ? 'Actualizar' : 'Agregar al Catálogo'}
		{cancelHref}
		{isSubmitting}
	/>
{/snippet}
