<script lang="ts">
	import { Button, Label, Input, Select, Checkbox, Textarea } from 'flowbite-svelte';
	import { toast } from 'svelte-sonner';
	import { goto } from '$app/navigation';
	import { untrack } from 'svelte';
	import { createLensCatalogItemForm, updateLensCatalogItemForm } from '$lib/remote/lenses.remote';
	import { CreatableSelect, type SelectOption } from '$lib/components/ui';
	import { LENS_TYPES, LENS_TYPE_LABELS, LENS_SOURCE_LABELS } from '$lib/schemas/lenses';
	import { scrollToFirstError } from '$lib/utils';
	import { generateUUID } from '$lib/utils/generateUUID';
	import type { LensCatalogItem } from '$lib/server/db/schema';

	type MaterialOption = SelectOption & { refractiveIndex?: number | null };

	type PendingSupplier = { pendingId: string; name: string };
	type PendingMaterial = { pendingId: string; name: string };

	type Props = {
		item?: LensCatalogItem | null;
		materials: { id: string; name: string; refractiveIndex?: number | null }[];
		suppliers: { id: string; name: string }[];
		cancelHref?: string;
	};

	let { item = null, materials = [], suppliers = [], cancelHref = '/lenses' }: Props = $props();

	let isSubmitting = $state(false);
	const isEdit = $derived(!!item);

	// Form instance
	let formInstanceId = $state(generateUUID());
	$effect(() => {
		untrack(() => {
			formInstanceId = generateUUID();
		});
	});

	const currentCreateForm = $derived(createLensCatalogItemForm.for(formInstanceId));
	const currentUpdateForm = $derived(
		updateLensCatalogItemForm.for(`${item?.id}-${formInstanceId}`)
	);
	const activeForm = $derived(isEdit ? currentUpdateForm : currentCreateForm);

	// Pending entities
	let pendingSuppliers = $state<PendingSupplier[]>([]);
	let pendingMaterials = $state<PendingMaterial[]>([]);

	// Form data
	let formData = $state({
		source: 'LAB' as string,
		supplierId: '',
		name: '',
		brand: '',
		technology: '',
		type: 'MONOFOCAL' as string,
		materialId: '',
		sphereMin: '-6.00',
		sphereMax: '+6.00',
		cylinderMin: '-4.00',
		cylinderMax: '0.00',
		additionMin: '',
		additionMax: '',
		isPhotochromic: false,
		isBlueCut: false,
		isAR: false,
		basePrice: '0',
		salePrice: '',
		deliveryDays: '',
		stock: '0',
		refractiveIndex: '',
		notes: ''
	});

	// Initialize when editing
	$effect(() => {
		if (item) {
			untrack(() => {
				formData = {
					source: item!.source,
					supplierId: item!.supplierId,
					name: item!.name,
					brand: item!.brand ?? '',
					technology: item!.technology ?? '',
					type: item!.type,
					materialId: item!.materialId,
					sphereMin: item!.sphereMin.toString(),
					sphereMax: item!.sphereMax.toString(),
					cylinderMin: item!.cylinderMin?.toString() ?? '',
					cylinderMax: item!.cylinderMax?.toString() ?? '',
					additionMin: item!.additionMin?.toString() ?? '',
					additionMax: item!.additionMax?.toString() ?? '',
					isPhotochromic: item!.isPhotochromic,
					isBlueCut: item!.isBlueCut,
					isAR: item!.isAR,
					basePrice: item!.basePrice.toString(),
					salePrice: item!.salePrice?.toString() ?? '',
					deliveryDays: item!.deliveryDays?.toString() ?? '',
					stock: item!.stock?.toString() ?? '0',
					refractiveIndex: item!.refractiveIndex?.toString() ?? '',
					notes: item!.notes ?? ''
				};
			});
		}
	});

	const showAddition = $derived(
		formData.type === 'PROGRESSIVE' ||
			formData.type === 'BIFOCAL' ||
			formData.type === 'OCCUPATIONAL'
	);

	const isFinished = $derived(formData.source === 'FINISHED');

	// Material/supplier options for CreatableSelect
	const materialOptions = $derived<MaterialOption[]>(
		materials.map((m) => ({
			id: m.id,
			name: m.refractiveIndex ? `${m.name} (${m.refractiveIndex})` : m.name,
			refractiveIndex: m.refractiveIndex
		}))
	);

	const supplierOptions = $derived<SelectOption[]>(
		suppliers.map((s) => ({ id: s.id, name: s.name }))
	);

	// Auto-fill refractive index from selected material
	$effect(() => {
		const selectedMat = materials.find((m) => m.id === formData.materialId);
		if (selectedMat?.refractiveIndex) {
			untrack(() => {
				formData.refractiveIndex = selectedMat.refractiveIndex!.toString();
			});
		}
	});

	// Auto-name generation
	// TODO: Check if the untrack is necessary
	let autoNameEnabled = $state(untrack(() => !item)); // Auto-name only for new items

	const autoGeneratedName = $derived(() => {
		if (!autoNameEnabled) return '';
		const parts: string[] = [];

		// Supplier name
		const sup = suppliers.find((s) => s.id === formData.supplierId);
		const pendingSup = pendingSuppliers.find((s) => s.pendingId === formData.supplierId);
		if (sup) parts.push(sup.name);
		else if (pendingSup) parts.push(pendingSup.name);

		// Material name
		const mat = materials.find((m) => m.id === formData.materialId);
		const pendingMat = pendingMaterials.find((m) => m.pendingId === formData.materialId);
		if (mat) parts.push(mat.name);
		else if (pendingMat) parts.push(pendingMat.name);

		// Type
		const typeLabel = LENS_TYPE_LABELS[formData.type as keyof typeof LENS_TYPE_LABELS];
		if (typeLabel) parts.push(typeLabel);

		// Technology
		if (formData.technology) parts.push(formData.technology);

		return parts.join(' · ');
	});

	// Apply auto-name when deps change
	$effect(() => {
		const name = autoGeneratedName();
		if (autoNameEnabled && name) {
			untrack(() => {
				formData.name = name;
			});
		}
	});

	// ── Pending entity handlers ──────────────────────────────────
	function handleCreatePendingSupplier(name: string): SelectOption {
		const pendingId = `pending_supplier_${generateUUID()}`;
		pendingSuppliers = [...pendingSuppliers, { pendingId, name }];
		return { id: pendingId, name, isPending: true };
	}

	function handleCreatePendingMaterial(name: string): SelectOption {
		const pendingId = `pending_material_${generateUUID()}`;
		pendingMaterials = [...pendingMaterials, { pendingId, name }];
		return { id: pendingId, name, isPending: true };
	}

	function getPendingName(pendingId: string): string | null {
		if (!pendingId.startsWith('pending_')) return null;
		const sup = pendingSuppliers.find((s) => s.pendingId === pendingId);
		if (sup) return sup.name;
		const mat = pendingMaterials.find((m) => m.pendingId === pendingId);
		if (mat) return mat.name;
		return null;
	}

	// Handle create result
	function handleCreateResult() {
		const allIssues = currentCreateForm.fields.allIssues?.() ?? [];
		if (allIssues.length > 0) {
			scrollToFirstError();
			return;
		}
		toast.success('Lente agregado al catálogo');
		// eslint-disable-next-line svelte/no-navigation-without-resolve
		goto('/lenses');
	}

	// Handle update result
	function handleUpdateResult() {
		const allIssues = currentUpdateForm.fields.allIssues?.() ?? [];
		if (allIssues.length > 0) {
			scrollToFirstError();
			return;
		}
		toast.success('Lente actualizado');
		// eslint-disable-next-line svelte/no-navigation-without-resolve
		goto('/lenses');
	}
</script>

<div class="mx-auto max-w-4xl">
	{#if isEdit && item}
		<!-- UPDATE FORM -->
		<form
			{...currentUpdateForm.enhance(async ({ submit }) => {
				isSubmitting = true;
				try {
					await submit();
					handleUpdateResult();
				} catch (e) {
					console.error(e);
					toast.error(e instanceof Error ? e.message : 'Error actualizando lente');
				} finally {
					isSubmitting = false;
				}
			})}
			class="space-y-6"
		>
			<input type="hidden" name="id" value={item.id} />
			{@render pendingHiddenInputs()}
			{@render formFields()}
			{@render formActions()}
		</form>
	{:else}
		<!-- CREATE FORM -->
		<form
			{...currentCreateForm.enhance(async ({ submit }) => {
				isSubmitting = true;
				try {
					await submit();
					handleCreateResult();
				} catch (e) {
					console.error(e);
					toast.error(e instanceof Error ? e.message : 'Error creando lente');
				} finally {
					isSubmitting = false;
				}
			})}
			class="space-y-6"
		>
			{@render pendingHiddenInputs()}
			{@render formFields()}
			{@render formActions()}
		</form>
	{/if}
</div>

{#snippet pendingHiddenInputs()}
	{#if formData.supplierId?.startsWith('pending_')}
		<input
			type="hidden"
			name="pendingSupplierName"
			value={getPendingName(formData.supplierId) ?? ''}
		/>
	{/if}
	{#if formData.materialId?.startsWith('pending_material_')}
		<input
			type="hidden"
			name="pendingMaterialName"
			value={getPendingName(formData.materialId) ?? ''}
		/>
		{#if formData.refractiveIndex}
			<input type="hidden" name="pendingMaterialRefractiveIndex" value={formData.refractiveIndex} />
		{/if}
	{/if}
{/snippet}

{#snippet formFields()}
	<!-- Source selector -->
	<div class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
		<h3 class="mb-4 text-lg font-semibold text-slate-800">Fuente del Cristal</h3>
		<div class="grid gap-4 md:grid-cols-2">
			<button
				type="button"
				class="rounded-lg border-2 p-4 text-left transition-all {formData.source === 'LAB'
					? 'border-blue-500 bg-blue-50/50'
					: 'border-slate-200 hover:border-slate-300'}"
				onclick={() => (formData.source = 'LAB')}
			>
				<p class="font-semibold text-slate-800">{LENS_SOURCE_LABELS.LAB}</p>
				<p class="text-sm text-slate-500">Cristal elaborado a medida en laboratorio</p>
			</button>
			<button
				type="button"
				class="rounded-lg border-2 p-4 text-left transition-all {formData.source === 'FINISHED'
					? 'border-indigo-500 bg-indigo-50/50'
					: 'border-slate-200 hover:border-slate-300'}"
				onclick={() => (formData.source = 'FINISHED')}
			>
				<p class="font-semibold text-slate-800">{LENS_SOURCE_LABELS.FINISHED}</p>
				<p class="text-sm text-slate-500">Cristal pre-fabricado con graduación lista</p>
			</button>
		</div>
		<input type="hidden" name="source" value={formData.source} />
	</div>

	<!-- Basic info -->
	<div class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
		<h3 class="mb-4 text-lg font-semibold text-slate-800">Información Básica</h3>
		<div class="grid gap-4 md:grid-cols-2">
			<div>
				<div class="mb-2 flex items-center justify-between">
					<Label for="lc_name">Nombre *</Label>
					{#if !isEdit}
						<label class="flex items-center gap-1.5 text-xs text-slate-500">
							<input
								type="checkbox"
								bind:checked={autoNameEnabled}
								class="h-3.5 w-3.5 rounded border-slate-300"
							/>
							Auto-generar
						</label>
					{/if}
				</div>
				<Input
					id="lc_name"
					name="name"
					bind:value={formData.name}
					placeholder="Ej: Novak · CR39 · Monofocal"
					required
					disabled={autoNameEnabled}
				/>
				{#if activeForm.fields.name?.issues()}
					<p class="mt-1 text-xs text-red-500">{activeForm.fields.name.issues()}</p>
				{/if}
				{#if autoNameEnabled}
					<p class="mt-1 text-xs text-slate-400">
						Se genera automáticamente desde los campos seleccionados
					</p>
				{/if}
			</div>
			<div>
				<Label for="lc_brand" class="mb-2">Marca</Label>
				<Input
					id="lc_brand"
					name="brand"
					bind:value={formData.brand}
					placeholder="Ej: Transitions, Essilor"
				/>
			</div>
		</div>

		<div class="mt-4 grid gap-4 md:grid-cols-2">
			<div>
				<Label for="lc_technology" class="mb-2">Tecnología</Label>
				<Input
					id="lc_technology"
					name="technology"
					bind:value={formData.technology}
					placeholder="Ej: Evo-S, Digital, FreeForm"
				/>
			</div>
			<div>
				<Label for="lc_type" class="mb-2">Tipo *</Label>
				<Select id="lc_type" name="type" bind:value={formData.type} required>
					{#each LENS_TYPES as t (t)}
						<option value={t}>{LENS_TYPE_LABELS[t]}</option>
					{/each}
				</Select>
			</div>
		</div>
	</div>

	<!-- Supplier & Material -->
	<div class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
		<h3 class="mb-4 text-lg font-semibold text-slate-800">Proveedor y Material</h3>
		<div class="grid gap-4 md:grid-cols-2">
			<CreatableSelect
				label="Proveedor *"
				name="supplierId"
				bind:value={formData.supplierId}
				options={supplierOptions}
				placeholder="Buscar proveedor..."
				required
				creatable
				onCreatePending={handleCreatePendingSupplier}
			/>
			<CreatableSelect
				label="Material *"
				name="materialId"
				bind:value={formData.materialId}
				options={materialOptions}
				placeholder="Buscar material..."
				required
				creatable
				onCreatePending={handleCreatePendingMaterial}
			/>
		</div>
		<div class="mt-4 grid gap-4 md:grid-cols-2">
			<div>
				<Label for="lc_ri" class="mb-2">Índice de Refracción</Label>
				<Input
					id="lc_ri"
					name="refractiveIndex"
					bind:value={formData.refractiveIndex}
					type="number"
					step="0.01"
					min="1.0"
					max="2.0"
					placeholder="1.50"
					class="font-mono"
				/>
				{#if formData.materialId?.startsWith('pending_material_') && formData.refractiveIndex}
					<p class="mt-1 text-xs text-blue-500">Se usará como índice para el nuevo material</p>
				{/if}
			</div>
		</div>
	</div>

	<!-- Optical ranges -->
	<div class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
		<h3 class="mb-4 text-lg font-semibold text-slate-800">Rangos Ópticos</h3>
		<div class="grid gap-4 md:grid-cols-2">
			<div>
				<Label class="mb-2">Esfera (mín / máx) *</Label>
				<div class="flex items-center gap-2">
					<Input
						name="sphereMin"
						bind:value={formData.sphereMin}
						type="number"
						step="0.25"
						placeholder="-6.00"
						size="sm"
						class="font-mono"
						required
					/>
					<span class="text-slate-400">a</span>
					<Input
						name="sphereMax"
						bind:value={formData.sphereMax}
						type="number"
						step="0.25"
						placeholder="+6.00"
						size="sm"
						class="font-mono"
						required
					/>
				</div>
				<p class="mt-1 text-xs text-slate-400">
					Ej: -6.00 a +6.00 · Positivo, negativo o mixto · Pasos 0.25
				</p>
			</div>
			<div>
				<Label class="mb-2">Cilindro (mín / máx)</Label>
				<div class="flex items-center gap-2">
					<Input
						name="cylinderMin"
						bind:value={formData.cylinderMin}
						type="number"
						step="0.25"
						max="0"
						placeholder="-4.00"
						size="sm"
						class="font-mono"
					/>
					<span class="text-slate-400">a</span>
					<Input
						name="cylinderMax"
						bind:value={formData.cylinderMax}
						type="number"
						step="0.25"
						max="0"
						placeholder="0.00"
						size="sm"
						class="font-mono"
					/>
				</div>
				<p class="mt-1 text-xs text-slate-400">Siempre ≤ 0 · Pasos de 0.25</p>
			</div>
		</div>

		{#if showAddition}
			<div class="mt-4">
				<Label class="mb-2">Adición (mín / máx)</Label>
				<div class="flex items-center gap-2" style="max-width: 50%;">
					<Input
						name="additionMin"
						bind:value={formData.additionMin}
						type="number"
						step="0.25"
						min="0"
						max="4.00"
						placeholder="0.75"
						size="sm"
						class="font-mono"
					/>
					<span class="text-slate-400">a</span>
					<Input
						name="additionMax"
						bind:value={formData.additionMax}
						type="number"
						step="0.25"
						min="0"
						max="4.00"
						placeholder="3.50"
						size="sm"
						class="font-mono"
					/>
				</div>
				<p class="mt-1 text-xs text-slate-400">Siempre ≥ 0 · Pasos de 0.25</p>
			</div>
		{/if}
	</div>

	<!-- Price, Delivery, Stock -->
	<div class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
		<h3 class="mb-4 text-lg font-semibold text-slate-800">Precio y Disponibilidad</h3>
		<div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
			<div>
				<Label for="lc_price" class="mb-2">Precio Compra ($) *</Label>
				<Input
					id="lc_price"
					name="basePrice"
					bind:value={formData.basePrice}
					type="number"
					step="0.01"
					min="0"
					class="font-mono"
					required
				/>
			</div>
			<div>
				<Label for="lc_sale_price" class="mb-2">Precio Venta ($)</Label>
				<Input
					id="lc_sale_price"
					name="salePrice"
					bind:value={formData.salePrice}
					type="number"
					step="0.01"
					min="0"
					placeholder="0.00"
					class="font-mono"
				/>
			</div>
			<div>
				<Label for="lc_delivery" class="mb-2">Días de entrega</Label>
				<Input
					id="lc_delivery"
					name="deliveryDays"
					bind:value={formData.deliveryDays}
					type="number"
					min="0"
					placeholder="3"
				/>
			</div>
			<div>
				<Label for="lc_stock" class="mb-2">
					Stock
					{#if isFinished}
						<span class="ml-1 text-xs text-indigo-600">(Terminado)</span>
					{/if}
				</Label>
				<Input
					id="lc_stock"
					name="stock"
					bind:value={formData.stock}
					type="number"
					min="0"
					placeholder="0"
					class={isFinished ? 'border-indigo-300 ring-1 ring-indigo-200' : ''}
				/>
				{#if isFinished}
					<p class="mt-1 text-xs text-indigo-500">Los cristales terminados se manejan por stock</p>
				{/if}
			</div>
		</div>

		<div class="mt-4">
			<Label class="mb-2 text-sm text-slate-600">Características incluidas</Label>
			<div class="flex flex-wrap items-center gap-6">
				<Checkbox name="isPhotochromic" bind:checked={formData.isPhotochromic}>
					Fotocromático
				</Checkbox>
				<Checkbox name="isBlueCut" bind:checked={formData.isBlueCut}>
					Blue Cut (Blue Block)
				</Checkbox>
				<Checkbox name="isAR" bind:checked={formData.isAR}>Antirreflejo (AR)</Checkbox>
			</div>
			<p class="mt-2 text-xs text-slate-400">
				Marca las características que ya vienen incluidas en este cristal
			</p>
		</div>
	</div>

	<!-- Notes -->
	<div class="rounded-xl border border-slate-200 bg-white p-6 shadow-sm">
		<h3 class="mb-4 text-lg font-semibold text-slate-800">Notas</h3>
		<Textarea
			id="lc_notes"
			name="notes"
			bind:value={formData.notes}
			rows={3}
			placeholder="Notas adicionales sobre este cristal..."
		/>
	</div>
{/snippet}

{#snippet formActions()}
	<div class="flex justify-end gap-3 pb-8">
		<Button color="alternative" href={cancelHref} disabled={isSubmitting}>Cancelar</Button>
		<Button type="submit" color="blue" disabled={isSubmitting}>
			{#if isSubmitting}
				<span
					class="mr-2 inline-block h-4 w-4 animate-spin rounded-full border-2 border-white border-t-transparent"
				></span>
			{/if}
			{isEdit ? 'Actualizar' : 'Agregar al Catálogo'}
		</Button>
	</div>
{/snippet}
