import { eq, and, inArray } from 'drizzle-orm';
import { db } from '$lib/server/db';
import type { DbOrTx } from '$lib/server/db/types';
import { surplusUnits, type SurplusUnit, type NewSurplusUnit } from '$lib/server/db/schema';
import { SurplusUnitStatus } from '$lib/shared/contracts/fulfillment';

// ============================================================================
// READS
// ============================================================================

export async function findSurplusUnitById(
	id: string,
	executor: DbOrTx = db
): Promise<SurplusUnit | null> {
	const [unit] = await executor.select().from(surplusUnits).where(eq(surplusUnits.id, id));
	return unit ?? null;
}

/**
 * Find all AVAILABLE surplus units for a given catalog item.
 * These can be used to fulfill a lens requirement instead of ordering new.
 */
export async function findAvailableSurplusByCatalogItemId(
	catalogItemId: string,
	executor: DbOrTx = db
): Promise<SurplusUnit[]> {
	return executor
		.select()
		.from(surplusUnits)
		.where(
			and(
				eq(surplusUnits.catalogItemId, catalogItemId),
				eq(surplusUnits.status, SurplusUnitStatus.AVAILABLE)
			)
		);
}

/**
 * Find all AVAILABLE surplus units for multiple catalog items at once.
 * Returns a map of catalogItemId → available units.
 */
export async function findAvailableSurplusForItems(
	catalogItemIds: string[],
	executor: DbOrTx = db
): Promise<Map<string, SurplusUnit[]>> {
	if (catalogItemIds.length === 0) return new Map();

	const units = await executor
		.select()
		.from(surplusUnits)
		.where(
			and(
				inArray(surplusUnits.catalogItemId, catalogItemIds),
				eq(surplusUnits.status, SurplusUnitStatus.AVAILABLE)
			)
		);

	const map = new Map<string, SurplusUnit[]>();
	for (const unit of units) {
		const existing = map.get(unit.catalogItemId);
		if (existing) {
			existing.push(unit);
		} else {
			map.set(unit.catalogItemId, [unit]);
		}
	}
	return map;
}

/**
 * Get all surplus units generated by a specific sale.
 */
export async function findSurplusByOriginSaleId(
	saleId: string,
	executor: DbOrTx = db
): Promise<SurplusUnit[]> {
	return executor.select().from(surplusUnits).where(eq(surplusUnits.originSaleId, saleId));
}

// ============================================================================
// WRITES — Lifecycle movements
// ============================================================================

/**
 * Create a new surplus unit (typically from a pair purchase excess).
 */
export async function createSurplusUnit(
	data: NewSurplusUnit,
	executor: DbOrTx = db
): Promise<SurplusUnit> {
	const now = new Date();
	const [unit] = await executor
		.insert(surplusUnits)
		.values({
			...data,
			id: crypto.randomUUID(),
			status: SurplusUnitStatus.AVAILABLE,
			createdAt: now,
			updatedAt: now
		})
		.returning();
	return unit;
}

/**
 * Reserve a surplus unit for a sale (soft-lock before confirmation).
 * Only AVAILABLE units can be reserved.
 */
export async function reserveSurplusUnit(
	id: string,
	saleId: string,
	executor: DbOrTx = db
): Promise<SurplusUnit | null> {
	const now = new Date();
	const [unit] = await executor
		.update(surplusUnits)
		.set({
			status: SurplusUnitStatus.RESERVED,
			reservedForSaleId: saleId,
			reservedAt: now,
			updatedAt: now
		})
		.where(and(eq(surplusUnits.id, id), eq(surplusUnits.status, SurplusUnitStatus.AVAILABLE)))
		.returning();
	return unit ?? null;
}

/**
 * Consume a surplus unit (sale confirmed, unit is used).
 * Only RESERVED units can be consumed.
 */
export async function consumeSurplusUnit(
	id: string,
	saleId: string,
	executor: DbOrTx = db
): Promise<SurplusUnit | null> {
	const now = new Date();
	const [unit] = await executor
		.update(surplusUnits)
		.set({
			status: SurplusUnitStatus.CONSUMED,
			consumedBySaleId: saleId,
			consumedAt: now,
			updatedAt: now
		})
		.where(and(eq(surplusUnits.id, id), eq(surplusUnits.status, SurplusUnitStatus.RESERVED)))
		.returning();
	return unit ?? null;
}

/**
 * Release a reserved surplus unit back to AVAILABLE (sale cancelled or plan changed).
 * Only RESERVED units can be released.
 */
export async function releaseSurplusUnit(
	id: string,
	executor: DbOrTx = db
): Promise<SurplusUnit | null> {
	const now = new Date();
	const [unit] = await executor
		.update(surplusUnits)
		.set({
			status: SurplusUnitStatus.AVAILABLE,
			reservedForSaleId: null,
			reservedAt: null,
			updatedAt: now
		})
		.where(and(eq(surplusUnits.id, id), eq(surplusUnits.status, SurplusUnitStatus.RESERVED)))
		.returning();
	return unit ?? null;
}

/**
 * Void a surplus unit (e.g., damaged, lost, manual correction).
 * Can void from AVAILABLE or RESERVED status.
 */
export async function voidSurplusUnit(
	id: string,
	notes: string | null,
	executor: DbOrTx = db
): Promise<SurplusUnit | null> {
	const now = new Date();
	const [unit] = await executor
		.update(surplusUnits)
		.set({
			status: SurplusUnitStatus.VOID,
			notes,
			voidedAt: now,
			updatedAt: now
		})
		.where(
			and(
				eq(surplusUnits.id, id),
				inArray(surplusUnits.status, [SurplusUnitStatus.AVAILABLE, SurplusUnitStatus.RESERVED])
			)
		)
		.returning();
	return unit ?? null;
}

/**
 * Restore a consumed surplus unit back to AVAILABLE (sale cancelled — unit was never physically used).
 * Only CONSUMED units can be restored.
 */
export async function restoreSurplusUnit(
	id: string,
	executor: DbOrTx = db
): Promise<SurplusUnit | null> {
	const now = new Date();
	const [unit] = await executor
		.update(surplusUnits)
		.set({
			status: SurplusUnitStatus.AVAILABLE,
			reservedForSaleId: null,
			reservedAt: null,
			consumedBySaleId: null,
			consumedAt: null,
			updatedAt: now
		})
		.where(and(eq(surplusUnits.id, id), eq(surplusUnits.status, SurplusUnitStatus.CONSUMED)))
		.returning();
	return unit ?? null;
}
