import { describe, expect, it } from 'vitest';
import { LensInventoryMode, LensPriceType, LensType } from '$lib/shared/enums';
import { LensCatalogSource } from '$lib/shared/enums/lensTypes';
import type { CatalogLists, LensCatalogFormData } from './lensFormTypes';
import {
	buildAutoGeneratedName,
	buildMaterialOptions,
	buildSupplierOptions,
	differentiatorHelperTextFor,
	materialHelperTextFor,
	supplierHelperTextFor,
	type PendingLists
} from './lensFormDisplay';

const lists: CatalogLists = {
	suppliers: [{ id: 'sup-1', name: 'Novak' }],
	materials: [{ id: 'mat-1', name: 'Policarbonato' }],
	supplierTechnologies: [{ id: 'tech-1', name: 'Bluecut' }]
};

const emptyPending: PendingLists = {
	pendingSuppliers: [],
	pendingMaterials: [],
	pendingTechnologies: []
};

function formData(overrides: Partial<LensCatalogFormData> = {}): LensCatalogFormData {
	return {
		source: LensCatalogSource.FINISHED,
		supplierId: 'sup-1',
		name: '',
		type: LensType.MONOFOCAL,
		technologyId: '',
		differentiators: [],
		arColors: [],
		photochromicColors: [],
		materialId: 'mat-1',
		hasAr: false,
		hasBluecut: false,
		isPhotochromic: false,
		priceType: LensPriceType.PAIR,
		basePrice: '',
		salePrice: '',
		mountingPrice: '',
		shippingPrice: '',
		isTaxable: true,
		inventoryMode: LensInventoryMode.ON_DEMAND,
		stock: '',
		notes: '',
		...overrides
	};
}

describe('option builders', () => {
	it('maps catalog entries to id-name options', () => {
		expect(buildSupplierOptions(lists.suppliers)).toEqual([{ id: 'sup-1', name: 'Novak' }]);
		expect(buildMaterialOptions(lists.materials)).toEqual([{ id: 'mat-1', name: 'Policarbonato' }]);
	});
});

describe('helper texts', () => {
	it('guides empty, pending and registered states', () => {
		expect(supplierHelperTextFor('')).toContain('Selecciona o crea');
		expect(supplierHelperTextFor('pending_x')).toContain('no existe');
		expect(supplierHelperTextFor('sup-1')).toContain('ya esta registrado');
		expect(materialHelperTextFor('')).toContain('Selecciona o crea');
		expect(materialHelperTextFor('pending_x')).toContain('no existe');
		expect(materialHelperTextFor('mat-1')).toContain('listo para reutilizar');
	});

	it('suggests differentiators when available', () => {
		expect(differentiatorHelperTextFor(['UV400', 'Thin'])).toContain('UV400');
		expect(differentiatorHelperTextFor([])).toContain('Cilindro Alto 2');
	});
});

describe('buildAutoGeneratedName', () => {
	it('joins supplier, material, technology and type', () => {
		expect(buildAutoGeneratedName(formData({ technologyId: 'tech-1' }), lists, emptyPending)).toBe(
			'Novak · Policarbonato · Bluecut · Monofocal'
		);
	});

	it('falls back to pending names and treatments', () => {
		const pending: PendingLists = {
			pendingSuppliers: [{ pendingId: 'pending_s', name: 'NuevoSup' }],
			pendingMaterials: [],
			pendingTechnologies: []
		};

		expect(
			buildAutoGeneratedName(
				formData({
					supplierId: 'pending_s',
					materialId: '',
					differentiators: ['UV400'],
					hasAr: true,
					arColors: ['Verde'],
					hasBluecut: true,
					isPhotochromic: true,
					photochromicColors: ['Gris']
				}),
				lists,
				pending
			)
		).toBe('NuevoSup · UV400 · FOTO · (Gris) · AR · (Verde) · BLUE · Monofocal');
	});

	it('returns empty string without data', () => {
		expect(
			buildAutoGeneratedName(formData({ supplierId: '', materialId: '' }), lists, emptyPending)
		).toBe('Monofocal');
	});
});
