import {
	getLensTypeLabel,
	LensCatalogSource,
	LensInventoryMode,
	LensPriceType,
	LensType
} from '$lib/shared/enums';
import type { PendingEntity } from '$lib/components/ui';
import type { LensCatalogItem } from '$lib/server/db/schema';
import type { CatalogLists, LensCatalogFormData } from './lensFormTypes';

export const TECHNOLOGY_HELPER_TEXT =
	'Selecciona la tecnología de fabricación digital para este lente de laboratorio.';

export function parseCommaList(text: string): string[] {
	return text
		.split(',')
		.map((s) => s.trim())
		.filter(Boolean);
}

export function createInitialLensFormData(item: LensCatalogItem | null): LensCatalogFormData {
	return {
		source: (item?.source as LensCatalogFormData['source']) ?? LensCatalogSource.LAB,
		supplierId: item?.supplierId ?? '',
		name: item?.name ?? '',
		type: (item?.type as LensType) ?? LensType.MONOFOCAL,
		technologyId: item?.technologyId ?? '',
		differentiators: (item?.differentiators as string[]) ?? [],
		arColors: (item?.arColors as string[]) ?? [],
		photochromicColors: (item?.photochromicColors as string[]) ?? [],
		materialId: item?.materialId ?? '',
		hasAr: item?.hasAr ?? false,
		hasBluecut: item?.hasBluecut ?? false,
		isPhotochromic: item?.isPhotochromic ?? false,
		priceType: (item?.priceType as LensPriceType) ?? LensPriceType.UNIT,
		basePrice: item?.basePrice?.toString() ?? '0',
		salePrice: item?.salePrice?.toString() ?? '0',
		mountingPrice: item?.mountingPrice?.toString() ?? '0',
		shippingPrice: item?.shippingPrice?.toString() ?? '0',
		isTaxable: item?.isTaxable ?? false,
		inventoryMode:
			(item?.inventoryMode as LensInventoryMode) ?? LensInventoryMode.ON_DEMAND,
		stock: item?.stock != null ? item.stock.toString() : '0',
		notes: item?.notes ?? ''
	};
}

export interface PendingLists {
	pendingSuppliers: PendingEntity[];
	pendingMaterials: PendingEntity[];
	pendingTechnologies: PendingEntity[];
}

export function buildSupplierOptions(suppliers: CatalogLists['suppliers']) {
	return suppliers.map((s) => ({ id: s.id, name: s.name }));
}

export function buildMaterialOptions(materials: CatalogLists['materials']) {
	return materials.map((m) => ({ id: m.id, name: m.name }));
}

export function supplierHelperTextFor(supplierId: string): string {
	if (!supplierId) return 'Selecciona o crea el proveedor responsable de este lente.';
	if (supplierId.startsWith('pending_')) {
		return 'Este proveedor no existe. Se creara un nuevo registro al guardar.';
	}
	return 'Este proveedor ya esta registrado en el sistema.';
}

export function materialHelperTextFor(materialId: string): string {
	if (!materialId) return 'Selecciona o crea el material base del cristal.';
	if (materialId.startsWith('pending_')) {
		return 'Este material no existe. Se creara un nuevo registro al guardar.';
	}
	return 'Este material ya esta registrado y listo para reutilizar.';
}

export function differentiatorHelperTextFor(differentiators: string[]): string {
	return differentiators.length > 0
		? `Opcional: etiquetas descriptivas separadas por comas (sugeridas: ${differentiators.slice(0, 3).join(', ')}).`
		: 'Opcional: etiquetas descriptivas separadas por comas (ej. Cilindro Alto 2, UV400).';
}

export function buildAutoGeneratedName(
	formData: LensCatalogFormData,
	lists: CatalogLists,
	pending: PendingLists
): string {
	const parts: string[] = [];

	const sup = lists.suppliers.find((s) => s.id === formData.supplierId);
	const pendingSup = pending.pendingSuppliers.find((s) => s.pendingId === formData.supplierId);
	if (sup) parts.push(sup.name);
	else if (pendingSup) parts.push(pendingSup.name);

	const mat = lists.materials.find((m) => m.id === formData.materialId);
	const pendingMat = pending.pendingMaterials.find((m) => m.pendingId === formData.materialId);
	if (mat) parts.push(mat.name);
	else if (pendingMat) parts.push(pendingMat.name);

	if (formData.technologyId) {
		const tech = lists.supplierTechnologies.find((t) => t.id === formData.technologyId);
		const pendingTech = pending.pendingTechnologies.find(
			(t) => t.pendingId === formData.technologyId
		);
		if (tech) parts.push(tech.name);
		else if (pendingTech) parts.push(pendingTech.name);
	}

	if (formData.differentiators && formData.differentiators.length > 0) {
		parts.push(formData.differentiators.join(' · '));
	}

	if (formData.isPhotochromic) {
		parts.push('FOTO');
		if (formData.photochromicColors && formData.photochromicColors.length > 0) {
			parts.push(`(${formData.photochromicColors.join('/')})`);
		}
	}
	if (formData.hasAr) {
		parts.push('AR');
		if (formData.arColors && formData.arColors.length > 0) {
			parts.push(`(${formData.arColors.join('/')})`);
		}
	}
	if (formData.hasBluecut) parts.push('BLUE');

	const typeLabel = getLensTypeLabel(formData.type);
	if (typeLabel) parts.push(typeLabel);

	return parts.join(' · ');
}
