<script lang="ts">
	interface Props {
		name: string;
		autoNameEnabled: boolean;
		autoGeneratedName: string;
		differentiatorsText: string;
		arColorsText: string;
		photochromicColorsText: string;
	}

	let {
		name = $bindable(),
		autoNameEnabled = $bindable(),
		autoGeneratedName,
		differentiatorsText = $bindable(),
		arColorsText = $bindable(),
		photochromicColorsText = $bindable()
	}: Props = $props();
</script>

<section class="rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-700 dark:bg-slate-800">
	<h3 class="mb-4 font-heading text-lg font-semibold text-on-surface">Identificacion del producto</h3>
	<div class="space-y-4">
		<div class="flex items-center gap-2">
			<input type="checkbox" bind:checked={autoNameEnabled} id="autoName" class="rounded" />
			<label for="autoName" class="text-sm text-slate-600 dark:text-slate-300">Nombre automático</label>
			{#if autoNameEnabled}
				<span class="text-xs text-slate-500">({autoGeneratedName})</span>
			{/if}
		</div>
		<div>
			<label for="lens-name" class="mb-1.5 block text-[11px] font-semibold tracking-[0.12em] text-slate-500 uppercase">Nombre</label>
			<input id="lens-name" type="text" bind:value={name} disabled={autoNameEnabled} placeholder={autoGeneratedName || 'Nombre del cristal'} class="w-full rounded-lg border border-slate-300 bg-white px-3.5 py-2.5 text-sm disabled:bg-slate-100 dark:border-slate-600 dark:bg-slate-800 dark:text-white" />
		</div>
		<div>
			<label for="lens-differentiators" class="mb-1.5 block text-[11px] font-semibold tracking-[0.12em] text-slate-500 uppercase">Diferenciadores (separados por coma)</label>
			<input id="lens-differentiators" type="text" bind:value={differentiatorsText} placeholder="Ej: HD, Premium" class="w-full rounded-lg border border-slate-300 bg-white px-3.5 py-2.5 text-sm dark:border-slate-600 dark:bg-slate-800 dark:text-white" />
		</div>
		<div class="grid gap-4 md:grid-cols-2">
			<div>
				<label for="lens-arColors" class="mb-1.5 block text-[11px] font-semibold tracking-[0.12em] text-slate-500 uppercase">Colores AR</label>
				<input id="lens-arColors" type="text" bind:value={arColorsText} placeholder="Ej: Verde, Azul" class="w-full rounded-lg border border-slate-300 bg-white px-3.5 py-2.5 text-sm dark:border-slate-600 dark:bg-slate-800 dark:text-white" />
			</div>
			<div>
				<label for="lens-photochromicColors" class="mb-1.5 block text-[11px] font-semibold tracking-[0.12em] text-slate-500 uppercase">Colores fotocromáticos</label>
				<input id="lens-photochromicColors" type="text" bind:value={photochromicColorsText} placeholder="Ej: Gris, Marrón" class="w-full rounded-lg border border-slate-300 bg-white px-3.5 py-2.5 text-sm dark:border-slate-600 dark:bg-slate-800 dark:text-white" />
			</div>
		</div>
	</div>
</section>
